typedef unsigned char u8; typedef signed int i32; typedef unsigned int u32;
static volatile u8 *const out=(volatile u8*)0x00500000;
static volatile u8 *const in=(volatile u8*)0x00500100;
static volatile u8 *const call=(volatile u8*)0x00500400;
enum{END=0,PUSH=1,ADD=2,SUB=3,MUL=4,DIV=5,MOD=6,DUP=7,DROP=8,SWAP=9,OVER=10,DOT=11,EMIT=12,CR=13,ARGC=14,ARGNUM=15,LIT=16,TYPE=17,READFILE=18,WRITEFILE=19,EXISTS=20,TWODUP=21,TWODROP=22,NIP=23,TUCK=24,ROT=25,NEGATE=26,ABS=27,MIN=28,MAX=29,EQ=30,NE=31,LT=32,GT=33,ZEROEQ=34,BAND=35,BOR=36,BXOR=37,BINV=38,ONEPLUS=39,ONEMINUS=40,TWOMUL=41,TWODIV=42};
__attribute__((used,section(".forthprog"))) static u8 program[256]={'F','T','H','B'};
static i32 stack[64]; static int sp=0,pc=4,started=0,waiting=0,argpos=0; static u8 filebuf[240]; static int filelen=0;
static void putc_(int c){unsigned n=out[0];if(n<250){out[1+n]=(u8)c;out[0]=(u8)(n+1);}}
static void puts_(const char*s){while(*s)putc_(*s++);} static void push(i32 v){if(sp<64)stack[sp++]=v;else puts_("STACK OVERFLOW\n");} static i32 pop(void){if(sp)return stack[--sp];puts_("STACK UNDERFLOW\n");return 0;}
static i32 rd32(void){u32 v=(u32)program[pc]|((u32)program[pc+1]<<8)|((u32)program[pc+2]<<16)|((u32)program[pc+3]<<24);pc+=4;return(i32)v;}
static void number(i32 v){char b[12];int n=0;if(!v){putc_('0');putc_(' ');return;}if(v<0){putc_('-');v=-v;}while(v&&n<11){b[n++]=(char)('0'+v%10);v/=10;}while(n)putc_(b[--n]);putc_(' ');}
static int argc_(void){int i=0,n=0,inside=0;while(i<in[0]){int c=in[2+i++];if(c==' '||c=='\t'){inside=0;}else if(!inside){inside=1;n++;}}return n;}
static i32 argnum_(void){int n=in[0],neg=0,any=0;i32 v=0;while(argpos<n&&(in[2+argpos]==' '||in[2+argpos]=='\t'))argpos++;if(argpos<n&&in[2+argpos]=='-'){neg=1;argpos++;}while(argpos<n&&in[2+argpos]>='0'&&in[2+argpos]<='9'){any=1;v=v*10+in[2+argpos++]-'0';}while(argpos<n&&in[2+argpos]!=' '&&in[2+argpos]!='\t')argpos++;return any?(neg?-v:v):0;}
static void syscall_name(int off,int len,int op){int i;if(len>15)len=15;call[4]=call[5]=0;for(i=0;i<len;i++)call[16+i]=program[off+i];call[0]=(u8)op;call[1]=255;call[2]=(u8)len;}
int _start(void){if(!started){started=1;out[0]=0;in[1]=0;}if(waiting){int i,n=call[4]|(call[5]<<8);if(call[1])puts_("FILE ERROR\n");else if(waiting==1){filelen=n>240?240:n;for(i=0;i<filelen;i++)filebuf[i]=call[32+i];push((i32)(u32)filebuf);push(filelen);}else push(call[1]?0:1);waiting=0;}
for(;;){int op=program[pc++],a,b,l,o;if(op==END)return 0;if(op==PUSH){push(rd32());continue;}if(op==ADD||op==SUB||op==MUL||op==DIV||op==MOD){b=pop();a=pop();if((op==DIV||op==MOD)&&!b){puts_("DIVISION BY ZERO\n");return 1;}push(op==ADD?a+b:op==SUB?a-b:op==MUL?a*b:op==DIV?a/b:a%b);continue;}if(op==DUP){a=pop();push(a);push(a);continue;}if(op==DROP){pop();continue;}if(op==SWAP){b=pop();a=pop();push(b);push(a);continue;}if(op==OVER){b=pop();a=pop();push(a);push(b);push(a);continue;}if(op==TWODUP){b=pop();a=pop();push(a);push(b);push(a);push(b);continue;}if(op==TWODROP){pop();pop();continue;}if(op==NIP){b=pop();pop();push(b);continue;}if(op==TUCK){b=pop();a=pop();push(b);push(a);push(b);continue;}if(op==ROT){int c=pop();b=pop();a=pop();push(b);push(c);push(a);continue;}if(op==NEGATE){push(-pop());continue;}if(op==ABS){a=pop();push(a<0?-a:a);continue;}if(op==MIN||op==MAX){b=pop();a=pop();push(op==MIN?(a<b?a:b):(a>b?a:b));continue;}if(op==EQ||op==NE||op==LT||op==GT){b=pop();a=pop();push(op==EQ?(a==b?-1:0):op==NE?(a!=b?-1:0):op==LT?(a<b?-1:0):(a>b?-1:0));continue;}if(op==ZEROEQ){push(pop()==0?-1:0);continue;}if(op==BAND||op==BOR||op==BXOR){b=pop();a=pop();push(op==BAND?(a&b):op==BOR?(a|b):(a^b));continue;}if(op==BINV){push(~pop());continue;}if(op==ONEPLUS){push(pop()+1);continue;}if(op==ONEMINUS){push(pop()-1);continue;}if(op==TWOMUL){push(pop()*2);continue;}if(op==TWODIV){push(pop()/2);continue;}if(op==DOT){number(pop());continue;}if(op==EMIT){putc_(pop());continue;}if(op==CR){putc_('\n');continue;}if(op==ARGC){push(argc_());continue;}if(op==ARGNUM){push(argnum_());continue;}if(op==LIT){l=program[pc++];push((i32)(u32)&program[pc]);push(l);pc+=l;continue;}if(op==TYPE){l=pop();o=pop();while(l-->0)putc_(((u8*)(u32)o)[0]),o++;continue;}if(op==READFILE||op==EXISTS){l=pop();o=pop();syscall_name(o-(int)(u32)program,l,1);waiting=op==READFILE?1:2;return 2;}if(op==WRITEFILE){int dl=pop(),d=pop();l=pop();o=pop();if(dl>220)dl=220;syscall_name(o-(int)(u32)program,l,27);call[3]=(u8)dl;for(a=0;a<dl;a++)call[32+a]=((u8*)(u32)d)[a];waiting=2;return 2;}puts_("BAD OPCODE\n");return 1;}}